# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CVV',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Private',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Virtual_Source',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
    ]
