# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrakWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Topic_post_username', models.TextField()),
                ('Topic_title', models.TextField()),
                ('Topic_post_time', models.TextField()),
                ('Deal_divide_sales', models.TextField()),
                ('Topic_price_dollar', models.TextField()),
                ('Topic_sales_status', models.TextField()),
                ('Crwal_time', models.TextField()),
                ('Catagory', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Tech',
            new_name='Service',
        ),
    ]
