# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrakWeb', '0002_auto_20181017_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Password', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='basic',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cvv',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='private',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sex',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teach',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='virtual_source',
            name='Topic_id',
            field=models.IntegerField(null=True),
        ),
    ]
